### ISSUE TITLE
Horizontal rules not supported?

### ISSUE THREAD

**Issue by JadeByfield89** [commonsguy/cwac-anddown#21] opened 2017-10-06 18:51 UTC
Noticing that horizontal rules are not supported when markdown text is converted to html?

I have markdown that contains rules denoted by "---", and these should translate to solid line separations for sections etc, but when converted to HTML it looks like they get ignored/removed

I'm using 
AndDown andDown = new AndDown();
String result = andDown.markdownToHtml(markdownString);

But not getting any horizontal rules showing. Any help?

**Comment by commonsguy** [comment] 2017-10-06 19:03
`---` is converted by AndDown (via hoedown) to `<hr>` in the test that I just ran. Note that `Html.fromHtml()` does not support `<hr>`.

If that does not match what you are seeing, please provide me with a reproducible test case.

**Comment by JadeByfield89** [comment] 2017-10-06 19:19
Hm, so I am in fact using Html.fromHtml() on the resulting html string. However, it looks like Anddown does not show any <hr> tags in the converted result. Here is the markdown string I am trying to convert

> "Your question is asking about \n**Symbiotic Relationships**\n---\n## Introduction to Symbiosis\nSymbiosis refers to the close, often long-term, interaction between two organisms. \n\nThere are three types of symbiosis: **mutualism**, **commensalism**, and **parasitism**. Predation and competition are usually not included.\n![](https://d2gne97vdumgn3.cloudfront.net/api/file/TmCQjHlWQOKo1q9PVuAK)\n---\n## Parasitism\nParasitism is a relationship which benefits one organism at the expense of the other organism. One benefits, one is harmed.\n\nThe relationship aphids have with plants is an example of a parasitic symbiosis.\n![](https://d2gne97vdumgn3.cloudfront.net/api/file/y03Mp1OxT4WzDCTaamlO)\n---\n## Mutalism\nMutualism is a relationship in which both species benefit.\n\nLadybugs and plants have this symbiosis. Ladybugs eat aphids, so ladybugs benefit from the supply of food. The plant benefits because it is no longer eaten by the aphid.\n\n![](https://d2gne97vdumgn3.cloudfront.net/api/file/1DL4OqopRfqUIh8jQWPh)\n---\n## Commensalism\nCommensalism occurs when one species benefits and the other species neither benefits nor is harmed due to the relationship. \n\nFor example, the barnacles that travel on whales save energy, but they do not impede the speed of the whale.\n![](https://d2gne97vdumgn3.cloudfront.net/api/file/298PB4USTSOwCh82hh9L)\n---\n"

Once converted via Anddown, I log the result in logcat..but noticing that there are no <hr> tags included. Just <h2> <p> and <img> tags. Would love to know if you get the same result!

**Comment by JadeByfield89** [comment] 2017-10-06 19:20
`"Your question is asking about \n**Symbiotic Relationships**\n---\n## Introduction to Symbiosis\nSymbiosis refers to the close, often long-term, interaction between two organisms. \n\nThere are three types of symbiosis: **mutualism**, **commensalism**, and **parasitism**. Predation and competition are usually not included.\n![](https://d2gne97vdumgn3.cloudfront.net/api/file/TmCQjHlWQOKo1q9PVuAK)\n---\n## Parasitism\nParasitism is a relationship which benefits one organism at the expense of the other organism. One benefits, one is harmed.\n\nThe relationship aphids have with plants is an example of a parasitic symbiosis.\n![](https://d2gne97vdumgn3.cloudfront.net/api/file/y03Mp1OxT4WzDCTaamlO)\n---\n## Mutalism\nMutualism is a relationship in which both species benefit.\n\nLadybugs and plants have this symbiosis. Ladybugs eat aphids, so ladybugs benefit from the supply of food. The plant benefits because it is no longer eaten by the aphid.\n\n![](https://d2gne97vdumgn3.cloudfront.net/api/file/1DL4OqopRfqUIh8jQWPh)\n---\n## Commensalism\nCommensalism occurs when one species benefits and the other species neither benefits nor is harmed due to the relationship. \n\nFor example, the barnacles that travel on whales save energy, but they do not impede the speed of the whale.\n![](https://d2gne97vdumgn3.cloudfront.net/api/file/298PB4USTSOwCh82hh9L)\n---\n"`

**Comment by JadeByfield89** [comment] 2017-10-06 19:23
I stumbled across this and looks like I can achieve my result by creating a custom tag handler?
https://stackoverflow.com/questions/19444911/hr-tag-usage-in-android

So I am looking to first ensure that `<hr>` tags are included before writing that handler. Hope my question is clear!

**Comment by commonsguy** [comment] 2017-10-06 19:28
AFAIK, that's not a valid Markdown string. AFAIK, Markdown does not honor C escape sequences like `\n`.

My test was to use the `demo/` app, replacing the `res/raw/readme.txt` file with:

```markdown
There is nothing to install. `Hoedown` is composed of 4 `.c` files (`markdown.c`,
`buffer.c`, `stack.c`, and `autolink.c`) and their headers, so just throw them in your
project. Zero-dependency means zero-dependency. You might want to include `html.c`,
`html_smartypants.c` and `escape.c` if you want to use the included XHTML renderer, or
write your own renderer. Either way, it's all fun and joy.

If you are hardcore, you can use the included `Makefile` to build `Hoedown` into a dynamic
library, or to build the sample `hoedown` executable, which is just a commandline
Markdown to XHTML parser.

---

This should appear after the horizontal rule.
```

(which is the last two paragraphs of the existing text, plus the horizontal rule and following sentence)

When I log the converted text to LogCat, I get:

```html
<p>There is nothing to install. <code>Hoedown</code> is composed of 4 <code>.c</code> files (<code>markdown.c</code>,
<code>buffer.c</code>, <code>stack.c</code>, and <code>autolink.c</code>) and their headers, so just throw them in your
project. Zero-dependency means zero-dependency. You might want to include <code>html.c</code>,
<code>html_smartypants.c</code> and <code>escape.c</code> if you want to use the included XHTML renderer, or
write your own renderer. Either way, it&#39;s all fun and joy.</p>

<p>If you are hardcore, you can use the included <code>Makefile</code> to build <code>Hoedown</code> into a dynamic
library, or to build the sample <code>hoedown</code> executable, which is just a commandline
Markdown to XHTML parser.</p>

<hr>

<p>This should appear after the horizontal rule.</p>
```

So, remove the `\n` from your Markdown, replacing them with actual newlines, and see if that helps.

**Comment by JadeByfield89** [comment] 2017-10-06 19:36
My apologies, I'm using Postman to view the JSON response from our API and it looks like it automatically includes the `\n` characters. Viewing the response directly in a JSON viewer online yields me this below. Looks valid now, no? 


`content : "Your question is asking about **Symbiotic Relationships** --- ## Introduction to Symbiosis Symbiosis refers to the close, often long-term, interaction between two organisms. There are three types of symbiosis: **mutualism**, **commensalism**, and **parasitism**. Predation and competition are usually not included. ![](https://d2gne97vdumgn3.cloudfront.net/api/file/TmCQjHlWQOKo1q9PVuAK) --- ## Parasitism Parasitism is a relationship which benefits one organism at the expense of the other organism. One benefits, one is harmed. The relationship aphids have with plants is an example of a parasitic symbiosis. ![](https://d2gne97vdumgn3.cloudfront.net/api/file/y03Mp1OxT4WzDCTaamlO) --- ## Mutalism Mutualism is a relationship in which both species benefit. Ladybugs and plants have this symbiosis. Ladybugs eat aphids, so ladybugs benefit from the supply of food. The plant benefits because it is no longer eaten by the aphid. ![](https://d2gne97vdumgn3.cloudfront.net/api/file/1DL4OqopRfqUIh8jQWPh) --- ## Commensalism Commensalism occurs when one species benefits and the other species neither benefits nor is harmed due to the relationship. For example, the barnacles that travel on whales save energy, but they do not impede the speed of the whale. ![](https://d2gne97vdumgn3.cloudfront.net/api/file/298PB4USTSOwCh82hh9L) --- "`

When I convert this to html via Anddown, I get back everything except the needed `<hr>` tags. Just trying to ensure that I get back the expected converted result before I run off to go write that custom tag handler, and hopefully save me some headache here

**Comment by commonsguy** [comment] 2017-10-06 19:52
> Looks valid now, no?

There do not appear to be any newlines, and AFAIK `---` needs to be at the beginning of the line. That could be how you are pasting this into GitHub. Regardless, at this point, I need a sample set of Java code, or a plain text file (as an attachment), that is failing in order to try to reproduce this.

**Comment by JadeByfield89** [comment] 2017-10-06 20:21
[markdown_bug.txt](https://github.com/commonsguy/cwac-anddown/files/1363811/markdown_bug.txt)

Ok, attached is a plain text file showing the markdown string that we get back from our API call. That string is held by a field named `explainerContent`. After a simple null check, we try to do our conversion as follows

` if(explainerContent != null && !explainerContent.isEmpty()){
            AndDown andDown = new AndDown();
            String result = andDown.markdownToHtml(explainerContent);
            // Use a custom ImageGetter to replace all <img> tags found with Drawables throughout the text
            GlideImageGetter glideImageGetter = new GlideImageGetter(getContext(), binding.tvContent);
            Spanned spanned = Html.fromHtml(result, glideImageGetter, null);
            binding.tvContent.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "fonts/cerapro-regular.otf"));
            binding.tvContent.setText(spanned);
        }`

Our issue is simply the when we log `result` above, we see no `<hr>` tags. Please let me know if you can reproduce this, or need anything else from me. Thanks so much for your quick response and insight!

**Comment by commonsguy** [comment] 2017-10-06 20:29
I get `<hr>` tags for the first three, due to the space preceding the `---` (which surprises me, as I thought that it needed a newline). I do not get an `<hr>` for the fourth one (before `## Commensalism`), because there is no whitespace before it (I usually use a blank line). I do not get an `<hr>` for the last one (at the document end), because there is no whitespace after it.

Using the `demo/` app, replacing the contents of `res/raw/readme.txt` with the contents of your file, and logging the generated HTML, gives me:

```html
<p>Your question is asking about 
  <strong>Symbiotic Relationships</strong></p>
 
 <hr>
 
 <p>## Introduction to Symbiosis
  Symbiosis refers to the close, often long-term, interaction between two organisms. </p>
 
 <p>There are three types of symbiosis: <strong>mutualism</strong>, <strong>commensalism</strong>, and <strong>parasitism</strong>. Predation and competition are usually not included.
 <img src="https://d2gne97vdumgn3.cloudfront.net/api/file/TmCQjHlWQOKo1q9PVuAK" alt=""></p>
 
 <hr>
 
 <p>## Parasitism
 Parasitism is a relationship which benefits one organism at the expense of the other organism. One benefits, one is harmed.</p>
 
 <p>The relationship aphids have with plants is an example of a parasitic symbiosis.
 <img src="https://d2gne97vdumgn3.cloudfront.net/api/file/y03Mp1OxT4WzDCTaamlO" alt=""></p>
 
 <hr>
 
 <p>## Mutalism
 Mutualism is a relationship in which both species benefit.</p>
 
 <p>Ladybugs and plants have this symbiosis. Ladybugs eat aphids, so ladybugs benefit from the supply of food. The plant benefits because it is no longer eaten by the aphid.</p>
 
 <h2><img src="https://d2gne97vdumgn3.cloudfront.net/api/file/1DL4OqopRfqUIh8jQWPh" alt=""></h2>
 
 <h2>Commensalism</h2>
 
 <p>Commensalism occurs when one species benefits and the other species neither benefits nor is harmed due to the relationship. </p>
 
 <p>For example, the barnacles that travel on whales save energy, but they do not impede the speed of the whale.
 <img src="https://d2gne97vdumgn3.cloudfront.net/api/file/298PB4USTSOwCh82hh9L" alt="">
```

So, at this point, I am going to close this issue as not being reproducible. If you give me a complete Java project that reproduces your problem, I'll look at it.

**Closed by commonsguy** 2017-10-06 20:29 UTC
